### PR TITLE
Switch to SortableJS

### PR DESCRIPTION
**Pull request by michaelborn**
The jQuery UI plugin was not working - I'd get an error like `$.sortable` is undefined. I'm not sure if the custom UI build was broken, but I updated the extension to use [SortableJS](https://github.com/SortableJS/Sortable) to work around this.

I also added a `setTimeout()` with 2 second delay. This fixes an issue where the new Bolt 5 Vue rendering wasn't complete when the sortable code first ran. Hence, there would be no records to sort!

### CODE REVIEW

**Comment by philippjeschek** [comment]
Thanks!

**Comment by michaelborn** [comment]
Thank YOU, man! Any chance you could create a patch or minor release so I can use this in prod? :smiling_face_with_tear:

**Comment by philippjeschek** [comment]
Sure! Just created the 1.0.4 release tag
Should be available via packagist in a few minutes :)
https://packagist.org/packages/jeschek/dragsort

**Comment by michaelborn** [comment]
DUDE - thank you so much!

**Pull request merged**
